# Generated by Django 4.1.2 on 2023-10-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mealplanmaker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodIngredient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=50)),
                (
                    "FoodIngredient",
                    models.ManyToManyField(to="mealplanmaker.foodingredient"),
                ),
            ],
        ),
    ]
