# Generated by Django 4.1.2 on 2024-01-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mealplanmaker", "0002_foodingredient_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
