# Generated by Django 4.2.3 on 2024-02-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mealplanmaker", "0003_recipe_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodingredient",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
