# Generated by Django 4.2.3 on 2024-02-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mealplanmaker", "0004_foodingredient_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodingredient",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
